"use client";
import {useEffect,useState} from "react";
import {BarChart3,BookOpen,CalendarDays,FileText,Image,Lightbulb,MessageSquare,Newspaper,Plus,Settings,Trash2,Users} from "lucide-react";
const modules=[["overview","نظرة عامة",BarChart3],["content","المحتوى",Newspaper],["events","الفعاليات",CalendarDays],["programs","البرامج والمبادرات",Lightbulb],["library","التقارير والوثائق",FileText],["media","الوسائط",Image],["submissions","المشاركات",MessageSquare],["knowledge","معرفة المساعد",BookOpen],["users","المستخدمون والأدوار",Users],["settings","الإعدادات",Settings]] as const;
type Tab=typeof modules[number][0];type Row=Record<string,unknown>;
const contentType:Record<string,string>={content:"news",events:"events",programs:"programs",library:"reports"};
export function AdminDashboard(){const[token,setToken]=useState(""),[authenticated,setAuthenticated]=useState(false),[tab,setTab]=useState<Tab>("overview"),[data,setData]=useState<{items?:Row[]}|Row|null>(null),[status,setStatus]=useState("");
 const endpoint=(next:Tab)=>next==="overview"?"/api/admin/summary":(["content","events","programs","library"].includes(next)?"/api/admin/content":`/api/admin/${next}`);
 useEffect(()=>{fetch("/api/admin/auth").then(r=>r.json()).then(x=>{setAuthenticated(Boolean(x.authenticated));if(x.authenticated)void load("overview")}).catch(()=>undefined)},[]);
 async function login(e:React.FormEvent){e.preventDefault();setStatus("جارٍ تسجيل الدخول…");try{const r=await fetch("/api/admin/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token})});if(!r.ok)throw new Error();setToken("");setAuthenticated(true);setStatus("");void load("overview")}catch{setStatus("مفتاح الإدارة غير صحيح أو غير مفعّل.")}}
 async function logout(){await fetch("/api/admin/auth",{method:"DELETE"});setAuthenticated(false);setData(null);setStatus("")}
 async function load(next=tab){if(!authenticated&&next!=="overview")return;setStatus("جارٍ تحميل البيانات…");try{const r=await fetch(endpoint(next));if(!r.ok)throw new Error();setData(await r.json());setStatus("")}catch{setStatus("تعذر تحميل البيانات. سجّل الدخول ثم أعد المحاولة.")}}
 function choose(next:Tab){setTab(next);setData(null);void load(next)}
 async function create(e:React.FormEvent<HTMLFormElement>,resource:string){e.preventDefault();const form=e.currentTarget,body=Object.fromEntries(new FormData(form).entries());setStatus("جارٍ الحفظ…");try{const r=await fetch(resource==="content"?"/api/admin/content":`/api/admin/${resource}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error();form.reset();setStatus("تم الحفظ بنجاح.");void load(tab)}catch{setStatus("تعذر الحفظ. راجع الحقول.")}}
 async function remove(id:number){if(!confirm("حذف هذا السجل؟ لا يمكن التراجع عن الحذف."))return;try{const r=await fetch("/api/admin/content",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(!r.ok)throw new Error();setStatus("تم الحذف.");void load(tab)}catch{setStatus("تعذر حذف السجل.")}}
 async function publish(id:number){try{const r=await fetch("/api/admin/content",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status:"published"})});if(!r.ok)throw new Error();setStatus("نُشر المحتوى.");void load(tab)}catch{setStatus("تعذر نشر المحتوى.")}}
 const rows=(data&&"items" in data?(data.items||[]):[]) as Row[];
 if(!authenticated)return <main className="admin-login" dir="rtl"><form onSubmit={login}><img src="/eladl-logo.png" alt="شعار حزب العدل"/><p>لوحة إدارة البوابة</p><h1>دخول الفريق المخوّل</h1><label>مفتاح الإدارة<input autoFocus type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="مفتاح الدخول" required/></label><button>تسجيل الدخول</button>{status&&<p className="admin-status">{status}</p>}</form></main>;
 return <div className="admin-app" dir="rtl"><aside><div className="admin-brand"><img src="/eladl-logo.png" alt=""/><b>إدارة البوابة</b></div>{modules.map(([key,label,Icon])=><button className={tab===key?"active":""} onClick={()=>choose(key)} key={key}><Icon size={17}/>{label}</button>)}</aside><section className="admin-main"><header><div><p>أمانة ريادة الأعمال المركزية</p><h1>{modules.find(x=>x[0]===tab)?.[1]}</h1></div><button className="admin-logout" onClick={logout}>تسجيل الخروج</button></header>{status&&<p className="admin-status">{status}</p>}{tab==="overview"?<Overview data={data}/>:["content","events","programs","library"].includes(tab)?<div className="admin-grid"><ContentForm onSubmit={e=>create(e,"content")} initialType={contentType[tab]}/><Rows rows={rows} onRemove={remove} onPublish={publish}/></div>:tab==="settings"?<SettingsPanel/>:<ResourcePanel tab={tab} rows={rows} onSubmit={create}/>}</section></div>}
function Overview({data}:{data:Row|null}){const values=data?Object.entries(data):[];return <div className="admin-overview"><div className="metric-grid">{values.length?values.map(([key,value])=><div key={key}><strong>{String((value as {count?:number}).count??0)}</strong><span>{key}</span></div>):["المحتوى","المشاركات الجديدة","معرفة المساعد","الوسائط"].map(key=><div key={key}><strong>—</strong><span>{key}</span></div>)}</div><div className="admin-empty">أدخل مفتاح الإدارة لتحميل الإحصاءات الحية من قاعدة البيانات.</div></div>}
function ContentForm({onSubmit,initialType}:{onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;initialType:string}){return <form onSubmit={onSubmit} className="admin-form"><h2>إضافة محتوى جديد</h2><label>النوع<select name="type" defaultValue={initialType}><option value="news">خبر</option><option value="events">فعالية</option><option value="programs">برنامج</option><option value="initiatives">مبادرة</option><option value="reports">تقرير</option><option value="policies">سياسة/مقترح</option><option value="opportunities">فرصة</option><option value="resources">مورد</option><option value="calls">دعوة</option></select></label><label>الرابط المختصر<input name="slug" required placeholder="my-new-item"/></label><label>العنوان<input name="title" required/></label><label>التصنيف<input name="category" placeholder="مثال: تمويل"/></label><label>الملخص<textarea name="excerpt" required/></label><label>النص الكامل<textarea name="body" required/></label><label>الحالة<select name="status"><option value="draft">مسودة</option><option value="published">منشور</option></select></label><button><Plus size={16}/>حفظ المحتوى</button></form>}
function ResourcePanel({tab,rows,onSubmit}:{tab:Tab;rows:Row[];onSubmit:(e:React.FormEvent<HTMLFormElement>,resource:string)=>void}){if(tab==="submissions")return <div className="admin-grid"><section className="admin-empty"><h2>المشاركات الواردة</h2><p>تصل هنا الأفكار والمشكلات والمقترحات ورسائل التواصل. من الـAPI يمكن لفريق المراجعة تحديث حالة كل طلب.</p></section><Rows rows={rows}/></div>;const config:Record<string,{title:string;resource:string;fields:{name:string;label:string;type?:string;optional?:boolean}[]}>={media:{title:"إضافة وسائط",resource:"media",fields:[{name:"kind",label:"النوع"},{name:"title",label:"العنوان"},{name:"url",label:"رابط الصورة أو الفيديو"},{name:"alt",label:"وصف بديل",optional:true}]},knowledge:{title:"إضافة معرفة للمساعد",resource:"knowledge",fields:[{name:"question",label:"سؤال أو كلمات مفتاحية"},{name:"answer",label:"الإجابة",type:"textarea"},{name:"status",label:"الحالة"}]},users:{title:"إضافة مستخدم إداري",resource:"users",fields:[{name:"email",label:"البريد الإلكتروني",type:"email"},{name:"role",label:"الدور (admin / editor / reviewer)"}]}};const c=config[tab];return <div className="admin-grid"><form className="admin-form" onSubmit={e=>onSubmit(e,c.resource)}><h2>{c.title}</h2>{c.fields.map(f=><label key={f.name}>{f.label}{f.type==="textarea"?<textarea name={f.name} required={!f.optional}/>:<input name={f.name} type={f.type||"text"} required={!f.optional}/>}</label>)}<button><Plus size={16}/>حفظ</button></form><Rows rows={rows}/></div>}
function Rows({rows,token,onRemove,onPublish}:{rows:Row[];token?:string;onRemove?:(id:number)=>void;onPublish?:(id:number)=>void}){return <section className="content-table"><h2>البيانات الحالية</h2>{rows.length?<table><thead><tr><th>العنوان / الاسم</th><th>النوع / الدور</th><th>الحالة</th>{onRemove&&<th>إجراء</th>}</tr></thead><tbody>{rows.map(row=><tr key={String(row.id)}><td>{String(row.title||row.question||row.name||row.email||"—")}</td><td>{String(row.type||row.kind||row.role||"—")}</td><td>{String(row.status||"—")}</td>{onRemove&&typeof row.id==="number"&&<td className="row-actions">{row.status!=="published"&&<button onClick={()=>onPublish?.(row.id as number)}>نشر</button>}<button className="danger" onClick={()=>onRemove(row.id as number)} aria-label="حذف"><Trash2 size={14}/></button></td>}</tr>)}</tbody></table>:<p>أدخل مفتاح الإدارة ثم اختر القسم لتحميل البيانات.</p>}</section>}
function SettingsPanel(){return <div className="admin-empty"><h2>إعدادات التشغيل</h2><p>اضبط قيمة <b>ADMIN_TOKEN</b> كقيمة سرية في بيئة الاستضافة. تُدار قاعدة D1 وترحيلات البيانات ضمن المشروع، ولا تُحفظ أي مفاتيح داخل الكود أو المستودع.</p></div>}
