export type PortalItem={id?:number;slug:string;type:string;title:string;excerpt:string;body?:string;date?:string;publishedAt?:string;category:string;tags?:string;status?:string;image?:string;locale?:string};
export type NavGroup={label:string;href:string;children:{label:string;href:string}[]};
export const navigation:NavGroup[]=[
 {label:"عن الأمانة",href:"/about",children:[{label:"عن الأمانة",href:"/about"},{label:"الرؤية والرسالة",href:"/about/vision"},{label:"الأهداف الاستراتيجية",href:"/about/objectives"},{label:"القيادة",href:"/about/leadership"},{label:"الفريق",href:"/about/team"},{label:"الهيكل التنظيمي",href:"/about/structure"},{label:"شبكة المحافظات",href:"/about/governorates"}]},
 {label:"البرامج والفرص",href:"/programs",children:[{label:"البرامج",href:"/programs"},{label:"المبادرات",href:"/initiatives"},{label:"الفرص",href:"/opportunities"},{label:"دعم الشركات الناشئة",href:"/startup-support"},{label:"دعم المشروعات الصغيرة والمتوسطة",href:"/sme-support"},{label:"قصص النجاح",href:"/success-stories"}]},
 {label:"المرصد والسياسات",href:"/observatory",children:[{label:"مرصد ريادة الأعمال",href:"/observatory"},{label:"المشكلات والتحديات",href:"/observatory/problems"},{label:"الحلول المقترحة",href:"/observatory/solutions"},{label:"أوراق السياسات",href:"/observatory/policies"},{label:"التقارير",href:"/insights/reports"},{label:"الأبحاث",href:"/insights/research"},{label:"المنشورات",href:"/insights/publications"}]},
 {label:"المركز الإعلامي",href:"/news",children:[{label:"الأخبار",href:"/news"},{label:"الفعاليات",href:"/events"},{label:"فعاليات قادمة",href:"/events/upcoming"},{label:"فعاليات سابقة",href:"/events/past"},{label:"الدعوات والإعلانات",href:"/calls"},{label:"معرض الصور",href:"/media/photos"},{label:"معرض الفيديو",href:"/media/videos"}]},
 {label:"شارك",href:"/join",children:[{label:"انضم إلى المسار",href:"/join"},{label:"تطوع بخبرتك",href:"/volunteer"},{label:"أرسل فكرة",href:"/submit/idea"},{label:"أبلغ عن مشكلة",href:"/submit/problem"},{label:"قدّم مقترحًا",href:"/submit/proposal"},{label:"الشراكات",href:"/partnerships"},{label:"تواصل معنا",href:"/contact"}]}
];
export const content:PortalItem[]=[
 {slug:"central-secretariats-appointments",type:"news",title:"حزب العدل يستكمل بناء الأمانات المركزية المتخصصة",excerpt:"قرارات تنظيمية لتوسيع العمل المتخصص والاستفادة من الخبرات والكفاءات.",body:"يستمر حزب العدل في تطوير عمل الأمانات المركزية المتخصصة، بما يدعم حضور الخبرة العملية في الملفات المختلفة ويقرب البرامج من احتياجات الناس.",date:"13 أغسطس 2026",category:"تنظيم"},
 {slug:"entrepreneurship-reality-future",type:"news",title:"مائدة مستديرة: ريادة الأعمال بين الواقع والمستقبل",excerpt:"حوار حول التحديات التي تواجه رواد الأعمال ومسارات العمل الممكنة.",body:"ناقشت المائدة احتياجات رواد الأعمال وأهمية الحوار بين الجهات الداعمة ورواد الأعمال وصنّاع القرار، بما يساعد على الانتقال من التشخيص إلى برامج عملية.",date:"21 مايو 2025",category:"حوار"},
 {slug:"entrepreneurship-challenges",type:"initiatives",title:"مسابقات وتحديات ريادية",excerpt:"مسابقات أفكار وعروض على مستوى المحافظة ثم المستوى القومي، مع تغطية إعلامية كاملة.",body:"يُدرج هذا المسار ضمن حزمة البرامج والمبادرات المقترحة في الخطة الاستراتيجية، ويُعلن عن مواعيد وشروط المشاركة بعد اعتمادها.",date:"قيد الإعداد",category:"مبادرات",status:"قيد الإعداد"},
 {slug:"startup-support-pathway",type:"programs",title:"حاضنات ومسرّعات أعمال مصغّرة",excerpt:"برنامج احتضان قصير المدى للمشروعات الواعدة بالشراكة مع حاضنات أو مؤسسات قائمة.",body:"المسار المقترح مدته من 6 إلى 12 أسبوعًا، ويستهدف تحويل المشروعات الواعدة إلى نماذج عمل جاهزة للعرض على الرعاة أو الحاضنات.",date:"قيد الإعداد",category:"الشركات الناشئة",status:"قيد الإعداد"},
 {slug:"annual-impact-report",type:"reports",title:"التقرير السنوي للأثر",excerpt:"إصدار سنوي يتابع البرامج والشراكات والتغطية الجغرافية وفق منظومة مؤشرات الأداء.",body:"تلتزم الأمانة بإعداد تقرير أداء ربع سنوي للأمانة العامة، إلى جانب التقرير السنوي الرسمي وفق الخطة الاستراتيجية.",date:"يصدر بعد التنفيذ",category:"تقارير",status:"قيد الإعداد"},
 {slug:"entrepreneurship-policy-dialogues",type:"problems",title:"تحديات ريادة الأعمال",excerpt:"مساحة منظمة لاستقبال التحديات ومناقشتها مع الأطراف المعنية تمهيدًا لتوصيات قابلة للتنفيذ.",body:"تقوم الحوارات الوطنية لريادة الأعمال على جمع صانعي القرار وأصحاب المصلحة. ويُنشر أي تحدٍ أو توصية بعد مراجعة الأمانة للمصادر والسياق.",date:"مفتوح للاستماع",category:"مرصد",status:"مفتوح للاستماع"},
 {slug:"entrepreneurship-policy-paper",type:"policies",title:"ورقة سياسات ريادة الأعمال",excerpt:"مخرج معرفي لحوارات السياسات يجمع التحديات والتوصيات والحلول المقترحة.",body:"لا تمثل هذه الصفحة موقفًا نهائيًا قبل المراجعة والاعتماد. تُنشر النسخة الكاملة والوثائق المساندة من لوحة الإدارة عند جاهزيتها.",date:"قيد الإعداد",category:"سياسات",status:"قيد الإعداد"},
 {slug:"founder-office-hours",type:"events",title:"ساعات مكتبية لرواد الأعمال",excerpt:"جلسات قصيرة مع خبراء لمناقشة التحديات التشغيلية والتمويلية وبناء الشراكات.",body:"صيغة فعاليات عملية قيد التحضير؛ تتضمن جلسات منظمة واستقبالًا مسبقًا للأسئلة لضمان استفادة عملية للمشاركين.",date:"سيُعلن الموعد قريبًا",category:"جلسات خبراء",status:"قريبًا"},
 {slug:"partnership-call",type:"calls",title:"دعوة للتعاون مع الجامعات والجهات الداعمة",excerpt:"فتح باب التواصل لتصميم برامج مشتركة تخدم رواد الأعمال والشباب في المحافظات.",body:"تدعو الأمانة الجهات الراغبة في التعاون إلى تقديم نبذة عن الخبرات والمسارات المقترحة، ليجري التواصل مع الجهة المناسبة داخل فريق العمل.",date:"مفتوح",category:"شراكات",status:"مفتوح"},
 {slug:"entrepreneurship-knowledge-library",type:"resources",title:"مكتبة ريادة الأعمال",excerpt:"تقارير سنوية وأوراق سياسات وتقارير الشركات الناشئة والمشروعات الصغيرة والاستثمار والذكاء الاصطناعي.",body:"المكتبة المعرفية جزء من الرؤية الرسمية للأمانة. تُضاف الوثائق المنشورة والمصادر المعتمدة بصورة منظمة وقابلة للبحث.",date:"يتحدث دوريًا",category:"معرفة"}
];
export const sectionConfig:Record<string,{title:string;intro:string;type?:string;kind?:"listing"|"about"|"form"}>={about:{title:"عن أمانة ريادة الأعمال المركزية",intro:"أمانة متخصصة تعمل على تحويل احتياجات رواد الأعمال إلى برامج وشراكات ومقترحات وسياسات قابلة للتنفيذ.",kind:"about"},programs:{title:"البرامج",intro:"مسارات تدريب وتمكين وربط بالسوق مصممة حول احتياجات رواد الأعمال والشباب.",type:"programs"},initiatives:{title:"المبادرات",intro:"مبادرات ذات أثر تربط التنمية المحلية بالابتكار والفرص الاقتصادية.",type:"initiatives"},opportunities:{title:"الفرص",intro:"فرص برامج وتمويل وتعاون يجري نشرها ومراجعتها من فريق الأمانة.",type:"opportunities"},"startup-support":{title:"دعم الشركات الناشئة",intro:"دليل مسارات عملية للشركات من الفكرة حتى الشراكات والنمو.",type:"programs"},"sme-support":{title:"دعم المشروعات الصغيرة والمتوسطة",intro:"موارد ومقترحات وشراكات تساعد على الاستدامة والتوسع.",type:"resources"},"success-stories":{title:"قصص النجاح",intro:"نماذج وتجارب عملية تُظهر أثر الدعم والابتكار والعمل المحلي.",type:"stories"},news:{title:"الأخبار",intro:"تغطية أعمال الأمانة والأنشطة المرتبطة بريادة الأعمال داخل حزب العدل.",type:"news"},events:{title:"الفعاليات",intro:"ندوات وجلسات خبراء وورش عمل وبرامج ميدانية ورقمية.",type:"events"},calls:{title:"الدعوات والإعلانات",intro:"فرص المشاركة والتعاون والتسجيل التي تفتحها الأمانة.",type:"calls"},observatory:{title:"مرصد ريادة الأعمال",intro:"منصة استماع وتحليل تربط المشكلة الموثقة بحل مقترح وخطة متابعة.",type:"problems"},insights:{title:"المعرفة والسياسات",intro:"تقارير وأبحاث وأوراق سياسات وموارد قابلة للتحميل والاطلاع.",type:"reports"},resources:{title:"الموارد",intro:"دليل منظم للفرص والأدوات والمصادر الداعمة لريادة الأعمال.",type:"resources"},partnerships:{title:"الشراكات",intro:"مساحة للتعاون مع الجامعات والقطاع الخاص والمستثمرين والجهات الداعمة.",type:"calls"},media:{title:"المركز الإعلامي",intro:"صور وفيديوهات ومواد مرئية توثق أنشطة الأمانة.",type:"media"},documents:{title:"الوثائق",intro:"مركز منظم للوثائق والتقارير والأدلة القابلة للرجوع إليها.",type:"reports"},faq:{title:"الأسئلة الشائعة",intro:"إجابات مباشرة عن الأمانة وبرامجها وطرق المشاركة.",kind:"about"},join:{title:"انضم إلى المسار",intro:"شارك كعضو أو خبير أو شريك أو رائد أعمال في برامج الأمانة.",kind:"form"},volunteer:{title:"تطوع بخبرتك",intro:"سجّل اهتمامك بالمساهمة في التدريب أو الإرشاد أو البحث أو التنظيم.",kind:"form"},contact:{title:"تواصل معنا",intro:"أرسل استفسارك أو طلب الشراكة وسيصل إلى فريق الأمانة.",kind:"form"}};
export const nestedConfig:Record<string,{title:string;intro:string;type:string}>={"about/vision":{title:"الرؤية والرسالة",intro:"رؤية تربط رواد الأعمال والمستثمرين والجامعات والقطاع الخاص والجهات الحكومية والشركاء الدوليين لدعم بيئة ريادة الأعمال والتنمية الاقتصادية.",type:"official"},"about/objectives":{title:"الأهداف الاستراتيجية",intro:"أهداف السنة الأولى كما توردها الخطة الاستراتيجية للأمانة.",type:"official"},"about/leadership":{title:"القيادة",intro:"مسؤوليات وأدوار فريق الأمانة المركزي.",type:"team"},"about/team":{title:"الفريق",intro:"فريق العمل والخبرات المشاركة في مسارات الأمانة.",type:"team"},"about/structure":{title:"الهيكل التنظيمي",intro:"تنظيم العمل بين المسارات المركزية والمحافظات.",type:"structure"},"about/governorates":{title:"شبكة المحافظات",intro:"مسارات استماع وتنفيذ محلية ترتبط بالمركز.",type:"resources"},"events/upcoming":{title:"فعاليات قادمة",intro:"سجّل اهتمامك بالأنشطة التي يجري التحضير لها.",type:"events"},"events/past":{title:"فعاليات سابقة",intro:"أرشيف جلسات الأمانة وورشها وبرامجها.",type:"events"},"observatory/problems":{title:"المشكلات والتحديات",intro:"قضايا منظمة بحسب القطاع والمحافظة والحالة.",type:"problems"},"observatory/solutions":{title:"الحلول المقترحة",intro:"مقترحات تنفيذية مرتبطة بالتحديات والشركاء.",type:"policies"},"observatory/policies":{title:"أوراق السياسات",intro:"مسودات ومقترحات قابلة للنقاش والتطوير.",type:"policies"},"insights/reports":{title:"التقارير",intro:"تقارير الأمانة والأوراق التنفيذية.",type:"reports"},"insights/research":{title:"الأبحاث",intro:"بحوث ودراسات مرتبطة بريادة الأعمال والعمل والتنمية المحلية.",type:"reports"},"insights/publications":{title:"المنشورات",intro:"إصدارات ومطبوعات قابلة للرجوع إليها.",type:"reports"},"media/photos":{title:"معرض الصور",intro:"توثيق بصري لفعاليات الأمانة.",type:"media"},"media/videos":{title:"معرض الفيديو",intro:"لقاءات وندوات ومحتوى مرئي.",type:"media"},"submit/idea":{title:"أرسل فكرة",intro:"فكرة برنامج أو مبادرة أو خدمة يمكن أن تضيف قيمة.",type:"form"},"submit/problem":{title:"أبلغ عن مشكلة",intro:"صف التحدي ومكانه ومن يتأثر به وما تعرفه من أدلة.",type:"form"},"submit/proposal":{title:"قدّم مقترحًا",intro:"أرسل مقترحك العملي أو ورقة أولية إلى فريق الأمانة.",type:"form"}};
const typePaths:Record<string,(slug:string)=>string>={news:s=>`/news/${s}`,events:s=>`/events/${s}`,programs:s=>`/programs/${s}`,initiatives:s=>`/initiatives/${s}`,opportunities:s=>`/opportunities/${s}`,problems:s=>`/observatory/problems/${s}`,policies:s=>`/observatory/policies/${s}`,reports:s=>`/insights/reports/${s}`,resources:s=>`/resources/${s}`,calls:s=>`/calls/${s}`,stories:s=>`/success-stories/${s}`,media:s=>`/media/photos/${s}`};
export function contentHref(item:PortalItem){return (typePaths[item.type]||((s:string)=>`/${item.type}/${s}`))(item.slug)}
export function getItems(type?:string){return type?content.filter(x=>x.type===type):content}
