import "../../english.css";import Link from "next/link";import {LocaleProvider} from "@/components/locale-provider";
import {ArrowRight,Search} from "lucide-react";

const pages:Record<string,{title:string;intro:string;items:string[]}>={
 "":{title:"Central Entrepreneurship Secretariat",intro:"El Adl Party’s digital portal for entrepreneurship policy, programmes, partnerships and public participation.",items:["Explore opportunities","Submit an idea or challenge","Read reports and policy proposals"]},
 about:{title:"About the Secretariat",intro:"A specialised central secretariat connecting entrepreneurs, investors, universities, the private sector, public institutions and international partners around practical action.",items:["Vision & mission","Strategic objectives","Organisation structure","Governorate network"]},
 programs:{title:"Programmes",intro:"Proposed pathways for schools, universities, founders, women and small businesses, to be published with approved dates and eligibility.",items:["School entrepreneurship","University pathways","Entrepreneurship challenges","Women’s empowerment","Venture support","Digital learning"]},
 initiatives:{title:"Initiatives",intro:"Practical initiatives under the Secretariat’s 2026–2027 strategic plan.",items:["Entrepreneurship challenges","Intensive camps","Local caravans","Annual flagship event"]},
 opportunities:{title:"Opportunities",intro:"Calls, programmes, partnerships and support pathways under review and publication.",items:["Funding and support","Programmes","Calls for collaboration"]},
 observatory:{title:"Entrepreneurship Observatory",intro:"A public-facing workflow from a documented challenge to proposed solutions, policy dialogue and accountable follow-up.",items:["Challenges","Proposed solutions","Policy paper","Annual impact reports"]},
 news:{title:"News",intro:"Updates on the Secretariat’s work and relevant El Adl Party activity.",items:["Announcements","Roundtables","Field activity"]},
 events:{title:"Events",intro:"Upcoming sessions, workshops, office hours and archived activities.",items:["Upcoming events","Past events","Registration"]},
 insights:{title:"Knowledge & Policy",intro:"Reports, research, publications and usable policy material.",items:["Reports","Research","Publications","Documents"]},
 partnerships:{title:"Strategic Partnerships",intro:"A multi-stakeholder pathway to support founders at every growth stage.",items:["Joint programmes","Mentorship","Innovation","Startup support"]},
 join:{title:"Get involved",intro:"Join as a member, volunteer, expert, partner or entrepreneur.",items:["Join","Volunteer","Submit an idea","Report a challenge"]},
 search:{title:"Search the portal",intro:"Use Arabic portal search for current published content, filters and categories.",items:["Search content","Browse categories"]}
};
export default async function EnglishPortal({params}:{params:Promise<{path?:string[]}>}){const path=(await params).path||[],key=path.slice(0,1).join("/"),page=pages[key]||{title:"Portal page",intro:"This page is being prepared in English. Arabic remains the primary, fully managed content language.",items:["Return to Arabic portal"]};return <LocaleProvider locale="en"><main className="english-portal"><header><Link href="/en" className="en-brand"><img src="/eladl-logo.png" alt="El Adl Party logo"/><span><b>El Adl Party</b><small>Central Entrepreneurship Secretariat</small></span></Link><nav aria-label="Primary navigation"><Link href="/en/about">About</Link><Link href="/en/programs">Programmes</Link><Link href="/en/observatory">Observatory</Link><Link href="/en/news">News</Link><Link href="/en/events">Events</Link><Link href="/">العربية</Link></nav></header><section className="en-hero"><p>ENTREPRENEURSHIP · EL ADL PARTY</p><h1>{page.title}</h1><p>{page.intro}</p></section><section className="en-content"><div className="en-grid">{page.items.map((x,i)=><article key={x}><span>0{i+1}</span><h2>{x}</h2><p>Explore this workstream, current updates and participation options through the portal.</p><Link href={key===""?"/":`/${key}`}><ArrowRight size={17}/> View in Arabic</Link></article>)}</div><Link className="en-search" href="/search"><Search size={18}/> Search the Arabic portal</Link></section></main></LocaleProvider>}
